# Generated by Django 5.2 on 2025-04-10 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotoristModel',
            fields=[
                ('id_motorist', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnh', models.CharField(max_length=255)),
                ('veiculo', models.CharField(max_length=255)),
            ],
        ),
    ]
